site_name: "Python中文库"

# 主题配置
theme:
  name: material
# 默认语言
  language: zh
# 默认配色
  palette:
    scheme: default
# logo
#  logo: assets/logo.png
#  favicon: images/favicon.png

# 插件配置
plugins:
  - search:
      lang:
        - en


extra:
  homepage: https://github.com/XueLiren/PyZW
